name: Deploy to server

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: compact arquivo
        run: |
          tar -cvzf buld-file.tar.gz index.html
      - name: copia arquivo para o server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: $ {{ secrets.SSH_KEY }}
          source: "buld-file.tar.gz"
          target: /tmp
        
  
